"""Crop generated artwork into exact native zone rectangles; no procedural painting.

Requires Pillow. Native masks are lossless RGBA DDS (both alpha and luminance).
The SVG preview depicts the original parchment atlas and masked texture controls.
"""
import base64
import json
import math
from pathlib import Path
from PIL import Image
from zone_border import build_border

ROOT = Path(__file__).resolve().parents[1]
zones = json.loads((ROOT / 'research/zones.json').read_text())
source = Image.open(ROOT / 'art/tamriel-color-v2.png').convert('RGB')
assert source.width == source.height
overrides = json.loads((ROOT / 'art/zone-art-sources.json').read_text())
for directory in ['textures/zones', 'masks', 'textures/borders', 'art/zone-borders']:
    (ROOT / directory).mkdir(parents=True, exist_ok=True)

def uri(path):
    return 'data:image/png;base64,' + base64.b64encode(path.read_bytes()).decode()

svg = ['<svg xmlns="http://www.w3.org/2000/svg" width="2048" height="2048" viewBox="0 0 2048 2048">',
       f'<image width="2048" height="2048" href="{uri(ROOT / "art/tamriel-original.png")}"/>']
lua = ['-- Generated by tools/package_zones.py from the user-exported native map blobs.',
       'KanaColorMapData = { zones = {']
border_svg = []
for z in zones:
    zone_source = source
    crop_space = False
    if str(z['id']) in overrides:
        override = overrides[str(z['id'])]
        crop_space = isinstance(override, dict) and override.get('space') == 'zone'
        filename = override['file'] if isinstance(override, dict) else override
        zone_source = Image.open(ROOT / 'art' / filename).convert('RGB')
    x, y, w, h = [z[k] for k in ('x', 'y', 'width', 'height')]
    tw, th = [max(32, 2 ** math.ceil(math.log2(v * 2048))) for v in (w, h)]
    if crop_space:
        crop = zone_source.resize((tw, th), Image.Resampling.LANCZOS)
    else:
        crop = zone_source.transform((tw, th), Image.Transform.EXTENT,
            (x * zone_source.width, y * zone_source.height,
             (x+w) * zone_source.width, (y+h) * zone_source.height),
            Image.Resampling.BICUBIC)
    crop.save(ROOT / f'textures/zones/{z["id"]}.dds', pixel_format='DXT1')
    mask = Image.open(ROOT / f'art/native-masks/{z["id"]}.png').convert('RGBA')
    mask.save(ROOT / f'masks/{z["id"]}.dds')
    fields = {'id': z['id'], 'x': x, 'y': y, 'width': w, 'height': h,
              'probeX': z['probeX'], 'probeY': z['probeY'], 'sourceMask': z['mask'],
              'mask': f'eso-kana-addons/KanaColorMap/masks/{z["id"]}.dds',
              'art': f'eso-kana-addons/KanaColorMap/textures/zones/{z["id"]}.dds'}
    border = build_border(mask, w, h, (tw, th))
    border.save(ROOT / f'textures/borders/{z["id"]}.dds')
    border.save(ROOT / f'art/zone-borders/{z["id"]}.png')
    fields['border'] = f'eso-kana-addons/KanaColorMap/textures/borders/{z["id"]}.dds'
    lua.append('    { ' + ', '.join(k + ' = ' + json.dumps(v) for k,v in fields.items()) + ' },')
    # Render from encoded DDS to include compression in visual QA.
    png = ROOT / f'art/native-masks/preview-{z["id"]}.png'
    Image.open(ROOT / f'textures/zones/{z["id"]}.dds').save(png)
    bounds = f'x="{x*2048}" y="{y*2048}" width="{w*2048}" height="{h*2048}"'
    mask_uri = uri(ROOT / f'art/native-masks/{z["id"]}.png')
    svg += [f'<defs><mask id="z{z["id"]}" maskUnits="userSpaceOnUse" style="mask-type:alpha" {bounds}><image {bounds} href="{mask_uri}" preserveAspectRatio="none"/></mask></defs>',
            f'<image {bounds} href="{uri(png)}" preserveAspectRatio="none" mask="url(#z{z["id"]})"/>']
    border_uri = uri(ROOT / f'art/zone-borders/{z["id"]}.png')
    border_svg.append(f'<image {bounds} href="{border_uri}" preserveAspectRatio="none"/>')
    png.unlink()
lua += ['} }', '']
(ROOT / 'Zones.lua').write_text('\n'.join(lua))
svg.extend(border_svg)
svg.append('</svg>')
(ROOT / 'art/tamriel-preview.svg').write_text('\n'.join(svg))
print(f'Packaged {len(zones)} zone textures + lossless native masks from {source.size}; wrote Zones.lua and SVG preview')
