-- UI labels/aliases, not game ability identity or a source of classification.
KanaEffects.Localization = KanaEffects.Localization or {}
KanaEffects.Localization.en = {
    families={aegis="Aegis",berserk="Berserk",breach="Breach",brittle="Brittle",brutality="Brutality",
        courage="Courage",cowardice="Cowardice",defile="Defile",endurance="Endurance",enervation="Enervation",
        evasion="Evasion",expedition="Expedition",force="Force",fortitude="Fortitude",heroism="Heroism",
        intellect="Intellect",lifesteal="Lifesteal",magickasteal="Magickasteal",maim="Maim",mangle="Mangle",
        mending="Mending",protection="Protection",resolve="Resolve",savagery="Savagery",slayer="Slayer",
        timidity="Timidity",toughness="Toughness",uncertainty="Uncertainty",vexation="Vexation",
        vitality="Vitality",vulnerability="Vulnerability"},
    categories={food="Food and drink",drink="Drink",xp="Experience",event="Event effects",service="Service effects",
        membership="Membership",cooldown="Service cooldown",justice="Justice",skillExperience="Skill experience"},
    levels={minor="Minor",major="Major"},
    reasons={unsupported_level="This level has no verified current catalog ID.",
        catalog_version_mismatch="The catalog has not been verified for this API version.",
        unknown_ability="Ability metadata is unavailable.", unknown_family="Unknown family.",
        unknown_category="Unknown category.", invalid_selector="Invalid selector."},
    categoryAliases={food={"food","meal","foodAndDrink"},xp={"xp","experience"}},
    -- Historical search vocabulary only; never creates active deprecated families.
    familyAliases={brutality={"sorcery"},savagery={"prophecy"}},
    picker={noHidden="No hidden effects.",unavailable="This effect is unavailable.",player="Player",target="Target",boss="Boss",commonGroup="Common",pvpRare="PvP / rare",title="Choose effect",hiddenTitle="Hidden effects",close="Close",searchHint="Effect name or ID",
        artificialId="Native effect ID",named="Named",common="Categories",active="Active",recent="Recent",pair="Minor + Major",minor="Only Minor",major="Only Major",
        anyFood="Any food",unknown="Unknown effect",unknownMetadata="Unknown metadata",catalog="Catalog",lastSeen="Last observed:",seenThisSession="Observed this session",seenTimeUnknown="Past observation; time unknown",
        enterHint="Click or Enter to choose",noResults="No matching effects.",scopeNotice="Observed sources are recipient unit tags; recents are past observations.",
        clear="Clear slot",restore="Restore",restoreAll="Restore all",hideEffect="Hide effect",restoreHint="Click or Enter to restore",
        hiddenNotice="Hidden in grids"},
}
KanaEffects.Localization.en.editor={
    sourcePlayer='Player',sourceTarget='Target',sourceBoss='Boss',setName='Set name',mainTab='General',panelName='Panel name',expression='Rule',ruleDocumentation='Rule reference',centerCoordinate='Center',panelType='Panel type',effectSelection='Show',allSelection='All effects',setSelection='Selected sets',namedAny='Include',namedOnly='Only named',namedExclude='Exclude',contextEdit='Edit panel',contextHide='Hide effect',
    addEffect='Add effect…',noFreeCells='No free cells',anyConditions='Any of these conditions',noConditions='No restrictions',otherDuration='Duration: other than Minor / Major',effectsTab='Effects',layoutTab='Layout',createSet='+ Create set',edit='Edit',chooseSet='Choose a set',assignments='Assigned cells',noAssignments='No effects yet',chooseCell='Add or change a cell',chooseEffect='Choose effect…',row='Row',column='Column',arrangement='Arrangement',fillDirection='Fill order',byRows='By rows',byColumns='By columns',iconsPerRow='Icons per row',iconsPerColumn='Icons per column',alignment='Alignment',alignLeft='Left',alignCenter='Center',alignRight='Right',alignTop='Top',alignBottom='Bottom',dimensions='Sizes',unitSize='px',unitSeconds='s',widgetActions='Panel',setActions='Set',offsets='Offsets',horizontal='Horizontal',vertical='Vertical',centerScreen='Center on screen',centerReference='Center on reference',
    includeHeading='Show sets',excludeHeading='Hide sets',none='None',growthAnchor='Grid growth point',growthHint='Point the grid grows from',resizeHint='Resize rows and columns',
    reference='Anchor to',
    referencePoint='Point on reference',
    resetScreen='Detach to screen',
    screen='Screen',
    actionBar='Action bar',
    resources='Resources',
    targetFrame='Target frame',
    diagnostics='Routing and overlap',
    evidence='Evidence',
    activeEvidence='Current observations (up to 250)',
    recentEvidence='Historical metadata (up to 100)',
    noComparison='No comparison',
    compareWith='Compare with',
    sampleTotal='%d total',
    metadataOverlap='Conditional metadata intersection: %d',
    overlap='Current observation intersection: %d',
    historyUnknown='Historical metadata: conditional rule evaluation. Polarity, duration and caster are unknown; activity, timers and simultaneous presence cannot be reconstructed. Zero does not prove universal disjointness.',
    lastObservation='Last observation',
    globalHide='Global hide',
    yes='Yes',
    no='No',
    tableBypass='Explicit table bypasses hiding',
    survivingPair='Pair contributors after filtering',
    contributors='Entry contributors',
    selectWidget='Select panel',
    routingCodes={explicit_slot='Matches explicit table slot',no_slot='No matching explicit slot',not_included='Matches no included set',excluded_set='Set exclusion has priority',global_hidden='Globally hidden before pair merging',named_policy='Rejected by named policy',included='Admitted to grid',wrong_source='Different recipient source',expired='Observation expired'},
    noMatchingCategory='No matching category',
    numericHint='↑ / ↓ adjusts by 1; Shift by 10.',outOfBounds='Outside the table',assignment='Cell',destinationRow='Move to row',destinationColumn='To column',recover='Move effect',editAssignment='Choose another effect…',clearAssignment='Clear cell',recoveryHint='Moving into an occupied cell swaps assignments. Other hidden addresses remain unchanged.',

    close='Close',cancel='Cancel',save='Save',discard='Discard changes',continue='Continue editing',test='Test',addWidget='+ Panel',sets='Sets',hiddenLibrary='Hidden',
    inspector='Panel settings',inspectorHint='Changes preview immediately. Save and Cancel are on the toolbar.',draftHint='Draft · outlines preserve the layout',newWidget='New panel',effects='effects',offscreen='Off screen',
    section='Section',general='Panel',appearance='Appearance',anchor='Position',composition='Composition',name='Name',type='Type',table='Assigned cells',grid='Automatic grid',source='Effect source',player='Player',target='Target',boss='Boss',
    columns='Columns',rows='Rows',count='Count',fixedAxis='Fixed axis',absent='Inactive',hidden='Hide',ghost='Ghost',opacity='Opacity',slotHint='Click a cell to select an effect. Explicit slots bypass grid rules and global hiding.',gridHint='Grids use effect sets. Empty outlines are service areas; they create no effects.',
    style='Style',over='Timer overlay',under='Timer below',right='Timer right',list='Name and timer',iconSize='Icon size',timerFontSize='Timer font',nameFontSize='Name font',rowWidth='Row width',gap='Gap',styleHint='Sizes use UI units. Minor above Major; only list style reserves names.',anchorHint='Anchor point on the panel. Changing it preserves the rectangle.',points={{'↖','↑','↗'},{'←','•','→'},{'↙','↓','↘'}},anchorRows={'Top','Middle','Bottom'},referenceScreen='Reference: screen',centerX='Horizontally',centerY='Vertically',
    named='Named families',any='Any',only='Only named',exclude='Exclude named',mergePairs='Merge Minor and Major',toggleInclude='Include / remove',toggleExclude='Exclude / remove',included='Included',excluded='Excluded',noSets='No sets yet.',duplicate='Duplicate panel',deleteWidget='Delete panel',invalidNumber='Enter a number.',invalidConfig='Check the values; the change was rejected.',openFailed='KanaEffects: editor could not open; editing canceled.',
    unsaved='Unsaved changes',unsavedHint='Save the complete draft, discard changes or continue editing?',demoHint='Test observations never enter history or settings.',live='Live effects',ordinary='Ordinary combat',setsHint='Sets can serve several panels. Exclusions take precedence.',set='Set',newSet='New set',addSet='+ Set',threshold='Long after',simple='Conditions',advanced='Advanced',references='Exclusions',explain='Explain match',preset='Preset',allEffects='All effects',combat='Combat',longFood='Food and long effects',advancedRuleHint='This set uses advanced conditions.',facet='Condition',unionHint='Any selected lifetime, category or origin. Kind and named-family choices are additional conditions.',noOtherSets='No other sets yet.',splitWith='Split with set…',manualInclude='Add effect…',manualExclude='Exclude an effect…',disjointHint='Splitting adds an explicit exclusion. Observed statistics do not prove universal disjointness.',
    condition='Condition',operation='Rule',addCondition='+ Condition',removeCondition='Remove selected condition',deleteSet='Delete set',refreshStats='Refresh observations',stats='%d matches from %d observations',statsHint='Current observations for the selected source. Zero overlap is not a universal proof.',observation='Observation',noObservations='No current observations for this source.',unknown='Unknown',expected='expected',fullDuration='full duration',namedYes='Named family',namedNo='No family',
    operations={['and']='All conditions',['or']='Any condition',['not']='Does not match',facet='Condition',selector='Effect / family / category'},facetNames={kind='Effect kind',lifetime='Lifetime',named='Named family',category='Category',origin='Origin',castBy='Applied by'},
    facetValues={kind={'buff','debuff','unknown'},lifetime={'short','long','permanent','toggle','unknown'},named={true,false},category={'food','drink','xp','event','service','membership','cooldown','justice','skillExperience'},origin={'skill','set','enchant','unknown'},castBy={'self','other','unknown'}},
    values={buff='Buff',debuff='Debuff',unknown='Unknown',short='Short',long='Long',permanent='Permanent',toggle='Toggle',skill='Skills',set='Sets',enchant='Enchants',self='Player',other='Other'},reasonCodes={['and']='All conditions',['or']='Any condition',['not']='Excluding condition',selector='Effect',facet='Condition',include_set='Includes set',exclude_set='Excludes set',included='Included in set',excluded='Excluded from set',not_included='Not included in set',unknown_set='Unavailable set'},
    errors={set_cycle='This reference creates a cycle. The previous rule is retained.',set_in_use='This set is referenced. Remove its references first.',unknown_set='Set not found. Check includes and excludes.',unknown_widget='This panel has been removed.',invalid_number='Number outside the allowed range.',invalid_threshold='Enter a duration greater than zero.',invalid_selector='No valid effect selected.',invalid_predicate='Check the set conditions.',settings_unavailable='Settings cannot be written; the draft remains open.',demo_unavailable='Test unavailable: catalog lacks enough supported families.',session_closed='Editing session is closed.'},
}
