-- Our UI translations; real individual effect names remain native API metadata.
KanaEffects.Localization = KanaEffects.Localization or {}
KanaEffects.Localization.ru = {
    families={aegis="Эгида",berserk="Ярость",breach="Пробой",brittle="Хрупкость",brutality="Жестокость",
        courage="Храбрость",cowardice="Трусость",defile="Осквернение",endurance="Выносливость",enervation="Ослабление",
        evasion="Уклонение",expedition="Ускорение",force="Сила",fortitude="Стойкость",heroism="Героизм",
        intellect="Интеллект",lifesteal="Похищение жизни",magickasteal="Похищение магии",maim="Увечье",mangle="Травма",
        mending="Исцеление",protection="Защита",resolve="Решимость",savagery="Свирепость",slayer="Убийца",
        timidity="Робость",toughness="Твердость",uncertainty="Неуверенность",vexation="Подавление исцеления",
        vitality="Жизненная сила",vulnerability="Уязвимость"},
    categories={food="Еда и напитки",drink="Напитки",xp="Опыт",event="Событийные эффекты",service="Служебные эффекты",
        membership="Подписка",cooldown="Служебная перезарядка",justice="Правосудие",skillExperience="Опыт навыков"},
    levels={minor="Малый",major="Великий"},
    reasons={unsupported_level="Для этого уровня нет подтверждённого ID в текущем каталоге.",
        catalog_version_mismatch="Каталог не проверен для этой версии API.",
        unknown_ability="Метаданные способности недоступны.",unknown_family="Неизвестное семейство.",
        unknown_category="Неизвестная категория.",invalid_selector="Некорректный селектор."},
    categoryAliases={food={"еда","пища"},xp={"опыт"}},
    familyAliases={courage={"отвага","Малая храбрость","Великая храбрость"},brutality={"колдовство"},savagery={"пророчество"}},
    picker={noHidden="Скрытых эффектов нет.",unavailable="Этот эффект сейчас недоступен.",player="Игрок",target="Цель",boss="Босс",commonGroup="Основные",pvpRare="PvP / редкие",title="Выбрать эффект",hiddenTitle="Скрытые эффекты",close="Закрыть",searchHint="Название или ID эффекта",
        artificialId="ID системного эффекта",named="Именованные",common="Категории",active="Активные",recent="Недавние",pair="Малый + великий",minor="Малый",major="Великий",
        anyFood="Любая еда",unknown="Неизвестный эффект",unknownMetadata="Метаданные неизвестны",catalog="Каталог",lastSeen="Последнее наблюдение:",seenThisSession="Наблюдалось в этой сессии",seenTimeUnknown="Прошлое наблюдение; время неизвестно",
        enterHint="Клик или Enter — выбрать",noResults="Совпадений нет.",scopeNotice="Источник — тег получателя. Недавние эффекты — прошлые наблюдения.",
        clear="Очистить слот",restore="Восстановить",restoreAll="Восстановить все",hideEffect="Скрыть эффект",restoreHint="Клик или Enter — восстановить",
        hiddenNotice="Скрытые в гридах"},
}
KanaEffects.Localization.ru.editor={
    setName='Название набора',mainTab='Основные',panelName='Название панели',expression='Правило',ruleDocumentation='Справочник правил',centerCoordinate='По центру',panelType='Тип панели',effectSelection='Показывать',allSelection='Все эффекты',setSelection='Выбранные наборы',namedAny='Показывать',namedOnly='Только их',namedExclude='Скрывать',contextEdit='Редактировать панель',contextHide='Скрыть эффект',
    addEffect='Добавить эффект…',noFreeCells='Нет свободных ячеек',anyConditions='Любое из условий',noConditions='Без ограничений',otherDuration='Длительность: кроме малых и великих',effectsTab='Эффекты',layoutTab='Раскладка',createSet='+ Создать набор',edit='Изменить',chooseSet='Выберите набор',assignments='Ячейки с эффектами',noAssignments='Эффектов пока нет',chooseCell='Добавить или изменить ячейку',chooseEffect='Выбрать эффект…',row='Строка',column='Столбец',arrangement='Расположение',fillDirection='Порядок заполнения',byRows='По строкам',byColumns='По столбцам',iconsPerRow='Иконок в строке',iconsPerColumn='Иконок в столбце',alignment='Выравнивание',alignLeft='Слева',alignCenter='По центру',alignRight='Справа',alignTop='Сверху',alignBottom='Снизу',dimensions='Размеры',unitSize='пкс',unitSeconds='с',widgetActions='Панель',setActions='Набор',offsets='Смещение',horizontal='По горизонтали',vertical='По вертикали',centerScreen='По центру экрана',centerReference='По центру опоры',
    includeHeading='Показывать наборы',excludeHeading='Не показывать',none='Нет',growthAnchor='Точка роста сетки',growthHint='Точка, от которой растёт грид',resizeHint='Изменить строки и столбцы',
    reference='Привязать к',
    referencePoint='Точка на опоре',
    resetScreen='Отвязать к экрану',
    screen='Экран',
    actionBar='Панель навыков',
    resources='Ресурсы',
    targetFrame='Рамка цели',
    diagnostics='Маршрут и пересечения',
    evidence='Данные',
    activeEvidence='Текущие наблюдения (до 250)',
    recentEvidence='История метаданных (до 100)',
    noComparison='Без сравнения',
    compareWith='Сравнить с',
    sampleTotal='всего %d',
    metadataOverlap='Условное совпадение метаданных: %d',
    overlap='Пересечение текущих наблюдений: %d',
    historyUnknown='Исторические метаданные: условная проверка правил. Тип, срок и применивший неизвестны; активность, таймеры и совместное присутствие не восстановлены. Ноль не доказывает универсальную непересекаемость.',
    lastObservation='Последнее наблюдение',
    globalHide='Глобальное скрытие',
    yes='Да',
    no='Нет',
    tableBypass='Явная таблица обходит скрытие',
    survivingPair='Компоненты пары после фильтрации',
    contributors='Наблюдения в представлении',
    selectWidget='Выбрать панель',
    routingCodes={explicit_slot='Совпало с явным слотом таблицы',no_slot='Нет подходящего явного слота',not_included='Не входит ни в один включённый набор',excluded_set='Исключение набора имеет приоритет',global_hidden='Удалён глобальным скрытием до объединения пары',named_policy='Не прошёл политику именованных эффектов',included='Допущен в грид',wrong_source='Другой источник наблюдения',expired='Наблюдение уже истекло'},
    noMatchingCategory='Нет подходящей категории',
    numericHint='↑ / ↓ — изменить на 1; Shift — на 10.',outOfBounds='За границами таблицы',assignment='Ячейка',destinationRow='В строку',destinationColumn='В колонку',recover='Перенести эффект',editAssignment='Выбрать другой эффект…',clearAssignment='Очистить ячейку',recoveryHint='Перенос в занятую ячейку меняет назначения местами. Остальные скрытые ячейки сохраняются.',

    close='Закрыть',cancel='Отменить',save='Сохранить',discard='Не сохранять',continue='Продолжить настройку',test='Тест',addWidget='+ Панель',sets='Наборы',hiddenLibrary='Скрытые',
    inspector='Настройки панели',inspectorHint='Изменения видны сразу. Сохранение и отмена — на панели.',draftHint='Черновик · рамки не меняют раскладку',newWidget='Новая панель',effects='эффектов',offscreen='За экраном',
    section='Раздел',general='Панель',appearance='Оформление',anchor='Позиция',composition='Состав',name='Имя',type='Тип',table='Таблица',grid='Сетка',source='Источник эффектов',sourcePlayer='Персонажа',sourceTarget='Цели',sourceBoss='Босса',player='Персонаж',target='Цель',boss='Босс',
    columns='Столбцы',rows='Строки',count='Количество',fixedAxis='Фиксировать',absent='Неактивные',hidden='Скрывать',ghost='Полупрозрачно',opacity='Непрозрачность',
    slotHint='Клик по ячейке выбирает эффект. Явные слоты обходят правила грида и скрытый список.',gridHint='Грид заполняется по наборам. Пустая рамка служебная; активных эффектов она не создаёт.',
    style='Стиль',over='Внутри',under='Снизу',right='Справа',list='С именем',iconSize='Иконка',timerFontSize='Шрифт таймера',nameFontSize='Шрифт имени',rowWidth='Ширина строки',gap='Зазор',styleHint='Размеры в UI-единицах. Minor сверху, Major снизу; названия есть только в стиле списка.',
    anchorHint='Выбранная точка панели. Смена точки сохраняет его прямоугольник.',points={{'↖','↑','↗'},{'←','•','→'},{'↙','↓','↘'}},anchorRows={'Верх','Середина','Низ'},referenceScreen='Опора: экран',centerX='По горизонтали',centerY='По вертикали',
    named='Именованные эффекты',any='Любые',only='Только они',exclude='Исключить',mergePairs='Объединять малый и великий',toggleInclude='Включить / убрать',toggleExclude='Исключить / убрать',included='Включены',excluded='Исключены',noSets='Наборов пока нет.',duplicate='Дублировать панель',deleteWidget='Удалить панель',
    invalidNumber='Введите число.',invalidConfig='Проверьте значения: изменение не применено.',openFailed='KanaEffects: редактор не удалось открыть; сессия отменена.',
    unsaved='Есть несохранённые изменения',unsavedHint='Сохранить весь черновик, отменить изменения или продолжить настройку?',demoHint='Тестовые наблюдения не попадают в историю и настройки.',live='Живые эффекты',ordinary='Обычный бой',
    setsHint='Набор можно использовать в нескольких панелях. Исключение имеет приоритет.',set='Набор',newSet='Новый набор',addSet='+ Набор',threshold='Долгие от',simple='Условия',advanced='Дополнительно',references='Связанные наборы',explain='Почему совпало',preset='Пресет',allEffects='Все эффекты',combat='Боевые',longFood='Еда и долгие',
    advancedRuleHint='Этот набор использует сложные условия.',facet='Условие',unionHint='Любой из отмеченных сроков, категорий и источников. Тип и именованность — дополнительные условия.',noOtherSets='Других наборов пока нет.',splitWith='Разделить с набором…',manualInclude='Добавить эффект…',manualExclude='Исключить эффект…',disjointHint='Разделение записывает явное исключение. Статистика текущих наблюдений не доказывает непересекаемость всех возможных эффектов.',
    condition='Условие',operation='Правило',addCondition='+ Условие',removeCondition='Удалить выбранное условие',deleteSet='Удалить набор',refreshStats='Обновить наблюдения',stats='%d совпадений из %d наблюдений',statsHint='Показаны текущие наблюдения выбранного источника. Нулевое пересечение не доказывает универсальное.',observation='Наблюдение',noObservations='Сейчас наблюдений для этого источника нет.',unknown='Неизвестно',expected='ожидается',fullDuration='полная длительность',namedYes='Малые / великие',namedNo='Остальные',
    operations={['and']='Все условия', ['or']='Любое условие', ['not']='Не совпадает',facet='Условие',selector='Эффект или категория'},
    facetNames={kind='Тип эффекта',lifetime='Длительность',named='Именованные эффекты',category='Категория',origin='Происхождение',castBy='Кто применил'},
    facetValues={kind={'buff','debuff','unknown'},lifetime={'short','long','permanent','toggle','unknown'},named={true,false},category={'food','drink','xp','event','service','membership','cooldown','justice','skillExperience'},origin={'skill','set','enchant','unknown'},castBy={'self','other','unknown'}},
    values={buff='Баф',debuff='Дебаф',unknown='Неизвестно',short='Короткие',long='Долгие',permanent='Постоянные',toggle='Переключаемые',skill='Навыки',set='Комплекты',enchant='Зачарования',self='Игрок',other='Другой'},
    reasonCodes={['and']='Все условия', ['or']='Любое условие', ['not']='Исключающее условие',selector='Эффект',facet='Условие',include_set='Включение набора',exclude_set='Исключение набора',included='Входит в набор',excluded='Исключён из набора',not_included='Не входит в набор',unknown_set='Набор недоступен'},
    errors={set_cycle='Ссылка создаёт цикл между наборами. Сохранено прежнее правило.',set_in_use='Набор используется. Сначала уберите ссылки на него.',unknown_set='Набор не найден. Проверьте включения и исключения.',unknown_widget='Панель уже удалена.',invalid_number='Число вне допустимого диапазона.',invalid_threshold='Укажите длительность больше нуля.',invalid_selector='Выберите доступный эффект.',invalid_predicate='Проверьте условия набора.',settings_unavailable='Настройки недоступны для записи; черновик остаётся открытым.',demo_unavailable='Тест недоступен: в каталоге недостаточно подтверждённых семейств.',session_closed='Сессия настройки уже закрыта.'},
}
